### ISSUE TITLE
Today/Tomorrow as sunday

### ISSUE THREAD

**Issue by edwardhadders** [ksya/ha-nefiteasy#38]
Let me start with saying thanks everyone for the effort in this custom component for homeassistant.
I'm having isseus with enabling the Today as sunday and Tommorrow as sunday switches, when i enable the switch it 
immediately goes back to off and it doesnt change the setting when i look in nefit app.
i have the same problem with Fireplace and Holiday.
anyone else having this isseu?

**Comment by ksya** [comment]
Yes, its not just you. Something must have broken it.

**Comment by RobBie1221** [comment]
I'll see if I can reproduce it

**Comment by RobBie1221** [comment]
No need to reproduce, the error is quite obvious

**Comment by ksya** [comment]
I don't think this is fixed. I still have this issue actually. 
It's not just today/tomorrow as sunday, but also the UI lock for example. Can you take a look at this @RobBie1221 ?

**Comment by RobBie1221** [comment]
I will have a have look.

**Comment by RobBie1221** [comment]
Previous fix was not needed, url is imported as const and defined as "url", so that change did exactly nothing.

@edwardhadders @ksya As far as I can verify, this is purely a displaying error. If I flip a switch and verify the status in the Nefit app, I can see that it is actually switching. The switch is however flipping back in the UI. After some time (max 60 seconds), the switch gets the correct state. Can you verify whether this is the case? If so, I have the fix ready.

**Comment by edwardhadders** [comment]
@RobBie1221 this evening i have tested it again and everytime i toggle the switch it goes back to off after 1sec and after 60 sec it goes back to on just as you described
But when i open the app its doest go to on 
But you dont have this problem?

**Comment by RobBie1221** [comment]
Which switch are you testing? I used tomorrow as Sunday. One note maybe, the page in the Nefit app showing this switch doesn't seem to refresh itself. I have to leave that page and go back to it to see a change.

**Comment by ksya** [comment]
I dived in a little. Before all the changes (https://github.com/ksya/ha-nefiteasy/commit/b157f93c0da20961768c275c93c7146769f753d7), this happened:
```
2021-01-28 21:49:31 DEBUG (MainThread) [custom_components.nefiteasy.switch] Switch Nefit lockui ON, endpoint=/ecus/rrc/lockuserinterface.,
2021-01-28 21:49:31 DEBUG (MainThread) [custom_components.nefiteasy.nefit_entity] async_update called for lockui,
2021-01-28 21:49:31 DEBUG (MainThread) [custom_components.nefiteasy] Got update for lockui.,
2021-01-28 21:49:31 DEBUG (MainThread) [custom_components.nefiteasy] parse_message data {'id': '/ecus/rrc/lockuserinterface', 'type': 'stringValue', 'recordable': 0, 'writeable': 1, 'value': 'true'}
```
After setting a switch, it immediately gets an update.
Now it does not even seem to call the async_update function. I have added it like this again:
```
    async def async_update(self):
        """Add required data to coordinator."""
        _LOGGER.debug("async_update called for %s", self._key)
        await super().async_update()
```
I do not see it in the logs. Unfortunately I don't have time anymore to dive into this deeper.

**Comment by RobBie1221** [comment]
I saw the same thing, it does send the command, but there is no update from the device anymore, which result in a wrong state in the UI. I'll push some changes for it.

**Comment by RobBie1221** [comment]
Since the dataupdatecoordinator was introduced, entities have property `should_poll` to `False` because the update coordinator handles the updates. The system however now thinks that the integration get push updates. Once a switch is flipped, `async_update` is not called because of mentioned reason. The problem however is that there is no push update when this data changes, it has to wait for a normal run of the update coordinator.

It's quite easy to manually call async_update, but perhaps that's a bit overkill as it updates all endpoints. I think it's better to trigger an update request for a single endpoint. We only need to send the request, receiving is already handled.

I'll push some changes later today.

**Comment by ksya** [comment]
It don't think it's like that. I am pretty sure there is a message pushed by the server on the same endpoint after something is changed. I also don't see carbon messages being handles by parse_message anymore. 
Also the async update was per endpoint before. 

Polling is only needed for entities that are not in the main status update (uiStatus)

**Comment by edwardhadders** [comment]
@RobBie1221 even if i close the app and reopen it the status keeps off it doest change.
but some other strange thing is in my configuration.yaml i have added the filter rows that i only what to see the following
      sensors:
        - system_pressure
      switches:
        - today_as_sunday
        - tomorrow_as_sunday
but i am getting all switches and sensors.

**Comment by RobBie1221** [comment]
This is what I see, before the dataupdatecoordinator, indeed async_update was per endpoint. When I flip a switch (I checked with debugpy), following function is called:

```
async def async_update(self):
        """Request latest data."""
        _LOGGER.debug("async_update called for %s", self._key)
        event = self._client.events[self._key]
        event.clear()  # clear old event
        `self._client.nefit.get(self.get_endpoint())`
        try:
            await asyncio.wait_for(event.wait(), timeout=9)
        except asyncio.TimeoutError:
            _LOGGER.debug(
                "Did not get an update in time for %s %s.",
                self._client.serial,
                self._key,
            )
            event.clear()  # clear event
```

This function requests the endpoint which is then received. If I comment out `self._client.nefit.get(self.get_endpoint())` and flip a switch (to be clear, in the old code), there is no data received on the switch endpoint. I therefore conclude it is not pushed, it is asked for. Maybe you were not aware HA calls `async_update` after you flip a switch?

You can try it out yourself, once `should_poll` is `False` (basically it was true for all switches as they have an endpoint not in uiStatus), the `async_update` is not called anymore.

I then still come to my point, `async_update` is not called anymore, but also `async_update` requests all endpoints, which is a bit overkill imo.

**Comment by RobBie1221** [comment]
> @RobBie1221 even if i close the app and reopen it the status keeps off it doest change.
> but some other strange thing is in my configuration.yaml i have added the filter rows that i only what to see the following
> sensors:
> - system_pressure
> switches:
> - today_as_sunday
> - tomorrow_as_sunday
> but i am getting all switches and sensors.

The readme is outdated, since the integration got a config flow, all switches/sensors are added by default. You can disable the ones you don't need, it will not update them anymore.

**Comment by RobBie1221** [comment]
By the way, it is different with uiStatus items, I verified those are updated push based. Only the single endpoints are not.

**Comment by RobBie1221** [comment]
> @RobBie1221 even if i close the app and reopen it the status keeps off it doest change.
> but some other strange thing is in my configuration.yaml i have added the filter rows that i only what to see the following
> sensors:
> - system_pressure
> switches:
> - today_as_sunday
> - tomorrow_as_sunday
> but i am getting all switches and sensors.

Another thing, the today_as_sunday and tomorrow_as_sunday show some funky behavior, also when I use the version from before my changes. Yesterday it seemed to work, if I now switch on tomorrow_as_sunday, it switches in reality today_as_sunday.
I need to double check what is going on there.

If I use the preheating switch to test, it works reliable.

**Comment by ksya** [comment]
Okay good findings! Are you working on a fix? Then I will not work on fixing this issue :)

**Comment by ksya** [comment]
I tested one thing, and hoped it would only fetch the status of the device being switched, but you are right:
```
    async def async_turn_on(self, **kwargs) -> None:
        """Turn the entity on."""
        self.coordinator.nefit.put_value(self.get_endpoint(), "on")

        _LOGGER.debug(
            "Switch Nefit %s ON, endpoint=%s.", self._key, self.get_endpoint()
        )
        await self.coordinator.async_request_refresh()
```
So this does solve the issue, but too much information is fetched, and thus not nice enough

**Comment by RobBie1221** [comment]
Indeed. I am working on something more elegant.

**Comment by RobBie1221** [comment]
@ksya Do you know how the "Hot Water" switch is working and how I can verify that with the Nefit app? I can see it writes to an endpoint based on "clock" or "manual" mode, state of the switch is however fetched from uiStatus. I can't seem to change the value in uiStatus.

It's not working for me either when I rollback to an older version, so I wonder if that was ever functional.

**Comment by RobBie1221** [comment]
I also noticed home entrance detection is broken, that needs fixing too.

**Comment by ksya** [comment]
> 
> 
> @ksya Do you know how the "Hot Water" switch is working and how I can verify that with the Nefit app? I can see it writes to an endpoint based on "clock" or "manual" mode, state of the switch is however fetched from uiStatus. I can't seem to change the value in uiStatus.
> 
> It's not working for me either when I rollback to an older version, so I wonder if that was ever functional.

I'm not sure if it ever worked, maybe I was working on it and forgot about it. The working is described here:
https://github.com/robertklep/nefit-easy-http-server/issues/11

**Comment by ksya** [comment]
This one is fixed :)

**Comment by edwardhadders** [comment]
Dear @RobBie1221 and @ksya 

i just updated to the latest version but it isnt working for me?
just in case i removed the intergration and readded it after a reboot but still no luck.
am i doing someting wrong?

**Comment by RobBie1221** [comment]
If you switch on or off, does it still flip back?

**Comment by edwardhadders** [comment]
no its not flipping back its keeps on or off but when i check the nefitapp there is no change i have waited 15 min

**Comment by ksya** [comment]
> no its not flipping back its keeps on or off but when i check the nefitapp there is no change i have waited 15 min

It does for me. You need to leave the "Operating mode" page and enter again. I have tested both ways

**Comment by RobBie1221** [comment]
Do you have problems with the new version specifically or did you recently start using this integration and never got it working?
What happens if you restart the Nefit app and check again?

**Comment by edwardhadders** [comment]
ok this i strange i will try to explain.
When enabled today as sunday for the first time in home assistant it doesnt get changed in Nefit app even if i fully close the app and reopen no luck ether with leaving "Operating mode" and entering it again.
But after onetime enabling Today as sunday in the nefit app and waiting for home assistant to see the change it is working i can enable and disable it from home assistant 
after that i thought it was a coincidence but the same was for tomorrow as sunday first time you need to enable it in nefitapp after that it works from home assistant and nefit app
does this make any sense for you guys for me it doesnt :)
